package poe

var propertyRegexes = [][]string{
	{"#% increased maximum Life", "(\\d*?)% increased maximum Life"},
	{"#% increased maximum Energy Shield", "(\\d*?)% increased maximum Energy Shield"},
	{"#% increased maximum Mana", "(\\d*?)% increased maximum Mana"},
	{"#% increased Mana Regeneration Rate", "(\\d*?)% increased Mana Regeneration Rate"},
	{"#% increased Energy Shield Recharge Rate", "(\\d*?)% increased Energy Shield Recharge Rate"},

	{"#% reduced Mana Cost of Skills", "(\\d*?)% reduced Mana Cost of Skills"},
	{"#% increased Rarity of Items found", "(\\d*?)% increased Rarity of Items found"},

	{"+# Life gained for each Enemy hit by your Attacks", "\\+(\\d*?) Life gained for each Enemy hit by your Attacks"},
	{"+# Mana gained for each Enemy hit by your Attacks", "\\+(\\d*?) Mana gained for each Enemy hit by your Attacks"},
	{"+# Energy Shield gained for each Enemy hit by your Attacks", "\\+(\\d*?) Energy Shield gained for each Enemy hit by your Attacks"},
	{"#% of Physical Attack Damage Leeched as Life", "(.*?)% of Physical Attack Damage Leeched as Life"},
	{"#% of Physical Attack Damage Leeched as Mana", "(.*?)% of Physical Attack Damage Leeched as Mana"},

	{"#% increased Armour", "(\\d*?)% increased Armour"},
	{"#% increased Evasion Rating", "(\\d*?)% increased Evasion Rating"},

	{"#% increased Stun Recovery", "(\\d*?)% increased Stun Recovery"},
	{"#% faster start of Energy Shield Recharge", "(\\d*?)% faster start of Energy Shield Recharge"},
	{"#% reduced Freeze Duration on You", "(\\d*?)% reduced Freeze Duration on You"},
	{"#% reduced Shock Duration on You", "(\\d*?)% reduced Shock Duration on You"},
	{"#% reduced Chill Duration on You", "(\\d*?)% reduced Chill Duration on You"},

	{"+#% Chance to Block with Shields", "\\+(\\d*?)% Chance to Block with Shields"},
	{"#% additional Chance to Block Spells with Shields", "(\\d*?)% additional Chance to Block Spells with Shields"},
	{"#% additional Chance to Block Spells while Dual Wielding", "(\\d*?)% additional Chance to Block Spells while Dual Wielding"},
	{"#% additional Block Chance while Dual Wielding", "(\\d*?)% additional Block Chance while Dual Wielding"},
	{"#% additional Chance to Block with Staves", "(\\d*?)% additional Chance to Block with Staves"},
	{"#% additional Chance to Block Spells with Staves", "(\\d*?)% additional Chance to Block Spells with Staves"},

	{"#% chance to Knock Enemies Back on hit", "(\\d*?)% chance to Knock Enemies Back on hit"},
	{"#% increased Stun Duration on Enemies", "(\\d*?)% increased Stun Duration on Enemies"},
	{"#% increased Accuracy Rating", "(\\d*?)% increased Accuracy Rating"},

	{"#% increased Damage over Time", "(\\d*?)% increased Damage over Time"},
	{"#% increased Projectile Speed", "(\\d*?)% increased Projectile Speed"},
	{"#% increased Attack and Cast Speed", "(\\d*?)% increased Attack and Cast Speed"},

	{"#% increased Ignite Duration on Enemies", "(\\d*?)% increased Ignite Duration on Enemies"},
	{"#% increased Shock Duration on Enemies", "(\\d*?)% increased Shock Duration on Enemies"},
	{"#% increased Freeze Duration on Enemies", "(\\d*?)% increased Freeze Duration on Enemies"},

	{"#% chance to Ignite", "(\\d*?)% chance to Ignite"},
	{"#% chance to Shock", "(\\d*?)% chance to Shock"},
	{"#% chance to Freeze", "(\\d*?)% chance to Freeze"},

	{"+# to all Attributes", "\\+(\\d*?) all Attributes"},
	{"+# to Dexterity", "\\+(\\d*?) to Dexterity"},
	{"+# to Intelligence", "\\+(\\d*?) to Intelligence"},
	{"+# to Strength", "\\+(\\d*?) to Strength"},
	{"+# to Strength and Intelligence", "\\+(\\d*?) to Strength and Intelligence"},
	{"+# to Strength and Dexterity", "\\+(\\d*?) to Strength and Dexterity"},
	{"+# to Dexterity and Intelligence", "\\+(\\d*?) to Dexterity and Intelligence"},

	{"Minions have #% increased maximum Life", "(\\d*?)% increased Minion Life"},
	{"Minions deal #% increased Damage", "Minions deal (\\d*?)% increased Damage"},
	{"Minions have #% Chance to Block", "Minions have (\\d*?)% Chance to Block"},
	{"Minions have #% to all Elemental Resistances", "Minions have \\+(\\d*?)% to all Elemental Resistances"},

	{"#% increased Totem Life", "(\\d*?)% increased Totem Life"},
	{"#% increased Totem Damage", "Totems deal (\\d*?)% increased Damage"},
	{"Totems gain #% to all Elemental Resistances", "Totems gain \\+(\\d*?)% to all Elemental Resistances"},

	{"#% increased Mine Damage", "(\\d*?)% increased Mine Damage"},
	{"#% increased Mine Laying Speed", "(\\d*?)% increased Mine Laying Speed"},

	{"#% increased Trap Damage", "(\\d*?)% increased Trap Damage"},
	{"#% increased Trap Throwing Speed", "(\\d*?)% increased Trap Throwing Speed"},

	{"+#% to Fire Resistance", "\\+(\\d*?)% to Fire Resistance"},
	{"+#% to Cold Resistance", "\\+(\\d*?)% to Cold Resistance"},
	{"+#% to Lightning Resistance", "\\+(\\d*?)% to Lightning Resistance"},
	{"+#% to Cold and Lightning Resistances", "\\+(\\d*?)% to Cold and Lightning Resistances"},
	{"+#% to Fire and Lightning Resistances", "\\+(\\d*?)% to Fire and Lightning Resistances"},
	{"+#% to Fire and Cold Resistances", "\\+(\\d*?)% to Fire and Cold Resistances"},
	{"+#% to all Elemental Resistances", "\\+(\\d*?)% to all Elemental Resistances"},
	{"+#% to Chaos Resistance", "\\+(\\d*?)% to Chaos Resistance"},

	{"#% increased Attack Speed", "(\\d*?)% increased Attack Speed"},
	{"#% increased Attack Speed with Wands", "(\\d*?)% increased Attack Speed with Wands"},
	{"#% increased Attack Speed with Swords", "(\\d*?)% increased Attack Speed with Swords"},
	{"#% increased Attack Speed with Axes", "(\\d*?)% increased Attack Speed with Axes"},
	{"#% increased Attack Speed with Daggers", "(\\d*?)% increased Attack Speed with Daggers"},
	{"#% increased Attack Speed with Claws", "(\\d*?)% increased Attack Speed with Claws"},
	{"#% increased Attack Speed with Maces", "(\\d*?)% increased Attack Speed with Maces"},
	{"#% increased Attack Speed with Staves", "(\\d*?)% increased Attack Speed with Staves"},
	{"#% increased Attack Speed with Bows", "(\\d*?)% increased Attack Speed with Bows"},
	{"#% increased Attack Speed with One Handed Melee Weapons", "(\\d*?)% increased Attack Speed with One Handed Melee Weapons"},
	{"#% increased Attack Speed with Two Handed Melee Weapons", "(\\d*?)% increased Attack Speed with Two Handed Melee Weapons"},
	{"#% increased Attack Speed while holding a Shield", "(\\d*?)% increased Attack Speed while holding a Shield"},
	{"#% increased Attack Speed while Dual Wielding", "(\\d*?)% increased Attack Speed while Dual Wielding"},

	{"#% increased Cast Speed", "(\\d*?)% increased Cast Speed"},
	{"#% increased Cast Speed with Cold Skills", "(\\d*?)% increased Cast Speed with Cold Skills"},
	{"#% increased Cast Speed with Fire Skills", "(\\d*?)% increased Cast Speed with Fire Skills"},
	{"#% increased Cast Speed with Lightning Skills", "(\\d*?)% increased Cast Speed with Lightning Skills"},
	{"#% increased Cast Speed while holding a Shield", "(\\d*?)% increased Cast Speed while holding a Shield"},
	{"#% increased Cast Speed while wielding a Staff", "(\\d*?)% increased Cast Speed while wielding a Staff"},
	{"#% increased Cast Speed while Dual Wielding", "(\\d*?)% increased Cast Speed while Dual Wielding"},

	{"#% increased Physical Damage with Daggers", "(\\d*?)% increased Physical Damage with Daggers"},
	{"#% increased Physical Damage with Axes", "(\\d*?)% increased Physical Damage with Axes"},
	{"#% increased Physical Damage with Swords", "(\\d*?)% increased Physical Damage with Swords"},
	{"#% increased Physical Damage with Maces", "(\\d*?)% increased Physical Damage with Maces"},
	{"#% increased Physical Damage with Claws", "(\\d*?)% increased Physical Damage with Claws"},
	{"#% increased Physical Damage with Wands", "(\\d*?)% increased Physical Damage with Wands"},
	{"#% increased Physical Damage with Bows", "(\\d*?)% increased Physical Damage with Bows"},
	{"#% increased Physical Damage with Staves", "(\\d*?)% increased Physical Damage with Staves"},
	{"#% increased Physical Weapon Damage while Dual Wielding", "(\\d*?)% increased Physical Weapon Damage while Dual Wielding"},
	{"#% increased Physical Damage with One Handed Melee Weapons", "(\\d*?)% increased Physical Damage with One Handed Melee Weapons"},
	{"#% increased Physical Damage with Two Handed Melee Weapons", "(\\d*?)% increased Physical Damage with Two Handed Melee Weapons"},
	{"#% increased Melee Physical Damage while holding a Shield", "(\\d*?)% increased Melee Physical Damage while holding a Shield"},

	{"#% increased Damage", "(\\d*?)% increased Damage"},
	{"#% increased Cold Damage", "(\\d*?)% increased Cold Damage"},
	{"#% increased Fire Damage", "(\\d*?)% increased Fire Damage"},
	{"#% increased Lightning Damage", "(\\d*?)% increased Lightning Damage"},
	{"#% increased Physical Damage", "(\\d*?)% increased Physical Damage"},
	{"#% increased Chaos Damage", "(\\d*?)% increased Chaos Damage"},
	{"#% increased Spell Damage", "(\\d*?)% increased Spell Damage"},
	{"#% increased Melee Damage", "(\\d*?)% increased Melee Damage"},
	{"#% increased Projectile Damage", "(\\d*?)% increased Projectile Damage"},
	{"#% increased Area Damage", "(\\d*?)% increased Area Damage"},

	{"#% increased Spell Damage while Dual Wielding", "(\\d*?)% increased Spell Damage while Dual Wielding"},
	{"#% increased Spell Damage while holding a Shield", "(\\d*?)% increased Spell Damage while holding a Shield"},
	{"#% increased Spell Damage while wielding a Staff", "(\\d*?)% increased Spell Damage while holding a Shield"},

	{"#% increased Global Critical Strike Chance", "(\\d*?)% increased Global Critical Strike Chance"},
	{"#% increased Melee Critical Strike Chance", "(\\d*?)% increased Melee Critical Strike Chance"},
	{"#% increased Critical Strike Chance for Spells", "(\\d*?)% increased Critical Strike Chance for Spells"},
	{"#% increased Critical Strike Chance with Cold Skills", "(\\d*?)% increased Critical Strike Chance with Cold Skills"},
	{"#% increased Critical Strike Chance with Fire Skills", "(\\d*?)% increased Critical Strike Chance with Fire Skills"},
	{"#% increased Critical Strike Chance with Lightning Skills", "(\\d*?)% increased Critical Strike Chance with Lightning Skills"},
	{"#% increased Critical Strike Chance with Elemental Skills", "(\\d*?)% increased Critical Strike Chance with Elemental Skills"},
	{"#% increased Critical Strike Chance with One Handed Melee Weapons", "(\\d*?)% increased Critical Strike Chance with One Handed Melee Weapons"},
	{"#% increased Critical Strike Chance with Two Handed Melee Weapons", "(\\d*?)% increased Critical Strike Chance with Two Handed Melee Weapons"},
	{"#% increased Weapon Critical Strike Chance while Dual Wielding", "(\\d*?)% increased Weapon Critical Strike Chance while Dual Wielding"},

	{"#% increased Global Critical Strike Multiplier", "(\\d*?)% increased Global Critical Strike Multiplier"},
	{"#% increased Melee Critical Strike Multiplier", "(\\d*?)% increased Melee Critical Strike Multiplier"},
	{"#% increased Critical Strike Multiplier with Elemental Skills", "(\\d*?)% increased Critical Strike Multiplier with Elemental Skills"},
	{"#% increased Critical Strike Multiplier with Lightning Skills", "(\\d*?)% increased Critical Strike Multiplier with Lightning Skills"},
	{"#% increased Critical Strike Multiplier with Fire Skills", "(\\d*?)% increased Critical Strike Multiplier with Fire Skills"},
	{"#% increased Critical Strike Multiplier with Cold Skills", "(\\d*?)% increased Critical Strike Multiplier with Cold Skills"},
	{"#% increased Critical Strike Multiplier for Spells", "(\\d*?)% increased Critical Strike Multiplier for Spells"},
	{"#% increased Critical Strike Multiplier with One Handed Melee Weapons", "(\\d*?)% increased Critical Strike Multiplier with One Handed Melee Weapons"},
	{"#% increased Critical Strike Multiplier with Two Handed Melee Weapons", "(\\d*?)% increased Critical Strike Multiplier with Two Handed Melee Weapons"},
	{"#% increased Critical Strike Multiplier while Dual Wielding", "(\\d*?)% increased Critical Strike Multiplier while Dual Wielding"},
}
